import { GameObject } from './metadataNormalization';

export const INITIAL_GAMES: GameObject[] = [
  {
    game_id: 'SuperMarioWorldUSA',
    title: 'Super Mario World',
    system: 'Super Nintendo',
    system_id: 'snes',
    rom_url: 'https://archive.org/download/nointro.snes/Super%20Mario%20World%20%28USA%29.zip',
    cover_url: 'https://raw.githubusercontent.com/libretro/libretro-thumbnails/master/Nintendo_-_Super_Nintendo_Entertainment_System/Named_Boxarts/Super%20Mario%20World%20(USA).png',
    artwork_url: 'https://raw.githubusercontent.com/libretro/libretro-thumbnails/master/Nintendo_-_Super_Nintendo_Entertainment_System/Named_Snaps/Super%20Mario%20World%20(USA).png',
    description: 'A plumber and his dinosaur friend battle a turtle king to save a princess in Dinosaur Land.',
    year: 1990,
    publisher: 'Nintendo',
    developer: 'Nintendo EAD',
    players: 2,
    emulator_core: 'snes9x',
    playable: true,
    rom_size: 524288,
    compatibility_status: 'verified',
    checksum: null
  },
  {
    game_id: 'SuperMarioBros3USA',
    title: 'Super Mario Bros. 3',
    system: 'Nintendo Entertainment System',
    system_id: 'nes',
    rom_url: 'https://archive.org/download/nointro.nes/Super%20Mario%20Bros.%203%20%28USA%29.zip',
    cover_url: 'https://raw.githubusercontent.com/libretro/libretro-thumbnails/master/Nintendo_-_Nintendo_Entertainment_System/Named_Boxarts/Super%20Mario%20Bros.%203%20(USA).png',
    artwork_url: 'https://raw.githubusercontent.com/libretro/libretro-thumbnails/master/Nintendo_-_Nintendo_Entertainment_System/Named_Snaps/Super%20Mario%20Bros.%203%20(USA).png',
    description: 'The ultimate 8-bit platforming adventure. Fly with the Raccoon Suit and save the Mushroom World.',
    year: 1988,
    publisher: 'Nintendo',
    developer: 'Nintendo R&D4',
    players: 2,
    emulator_core: 'fceumm',
    playable: true,
    rom_size: 393216,
    compatibility_status: 'verified',
    checksum: null
  },
  {
    game_id: 'SonicTheHedgehogUSA',
    title: 'Sonic the Hedgehog',
    system: 'Sega Genesis',
    system_id: 'sega_genesis',
    rom_url: 'https://archive.org/download/nointro.md/Sonic%20the%20Hedgehog%20%28USA%2C%20Europe%29.zip',
    cover_url: 'https://raw.githubusercontent.com/libretro/libretro-thumbnails/master/Sega_-_Mega_Drive_-_Genesis/Named_Boxarts/Sonic%20the%20Hedgehog%20(USA,%20Europe).png',
    artwork_url: 'https://raw.githubusercontent.com/libretro/libretro-thumbnails/master/Sega_-_Mega_Drive_-_Genesis/Named_Snaps/Sonic%20the%20Hedgehog%20(USA,%20Europe).png',
    description: 'The debut of the fastest hedgehog alive. Spin dash through Green Hill Zone.',
    year: 1991,
    publisher: 'Sega',
    developer: 'Sonic Team',
    players: 1,
    emulator_core: 'genesis_plus_gx',
    playable: true,
    rom_size: 524288,
    compatibility_status: 'verified',
    checksum: null
  },
  {
    game_id: 'LegendOfZeldaUSA',
    title: 'The Legend of Zelda',
    system: 'Nintendo Entertainment System',
    system_id: 'nes',
    rom_url: 'https://archive.org/download/nointro.nes/Legend%20of%20Zelda%2C%20The%20%28USA%29.zip',
    cover_url: 'https://raw.githubusercontent.com/libretro/libretro-thumbnails/master/Nintendo_-_Nintendo_Entertainment_System/Named_Boxarts/Legend%20of%20Zelda,%20The%20(USA).png',
    artwork_url: 'https://raw.githubusercontent.com/libretro/libretro-thumbnails/master/Nintendo_-_Nintendo_Entertainment_System/Named_Snaps/Legend%20of%20Zelda,%20The%20(USA).png',
    description: 'It\'s dangerous to go alone! Take this.',
    year: 1986,
    publisher: 'Nintendo',
    developer: 'Nintendo R&D4',
    players: 1,
    emulator_core: 'fceumm',
    playable: true,
    rom_size: 131072,
    compatibility_status: 'verified',
    checksum: null
  },
  {
    game_id: 'PokemonEmeraldUSA',
    title: 'Pokemon Emerald',
    system: 'Game Boy Advance',
    system_id: 'gba',
    rom_url: 'https://archive.org/download/nointro.gba/Pokemon%20-%20Emerald%20Version%20%28USA%2C%20Europe%29.zip',
    cover_url: 'https://raw.githubusercontent.com/libretro/libretro-thumbnails/master/Nintendo_-_Game_Boy_Advance/Named_Boxarts/Pokemon%20-%20Emerald%20Version%20(USA,%20Europe).png',
    artwork_url: 'https://raw.githubusercontent.com/libretro/libretro-thumbnails/master/Nintendo_-_Game_Boy_Advance/Named_Snaps/Pokemon%20-%20Emerald%20Version%20(USA,%20Europe).png',
    description: 'Balance the forces of Groudon and Kyogre with Rayquaza in the Hoenn region.',
    year: 2004,
    publisher: 'Nintendo',
    developer: 'Game Freak',
    players: 1,
    emulator_core: 'mgba',
    playable: true,
    rom_size: 16777216,
    compatibility_status: 'verified',
    checksum: null
  },
  {
    game_id: 'CrashTeamRacingUSA',
    title: 'Crash Team Racing',
    system: 'PlayStation',
    system_id: 'psx',
    rom_url: 'https://archive.org/download/sony_playstation_usa_library/Crash%20Team%20Racing%20%28USA%29.zip',
    cover_url: 'https://raw.githubusercontent.com/libretro/libretro-thumbnails/master/Sony_-_PlayStation/Named_Boxarts/Crash%20Team%20Racing%20(USA).png',
    artwork_url: 'https://raw.githubusercontent.com/libretro/libretro-thumbnails/master/Sony_-_PlayStation/Named_Snaps/Crash%20Team%20Racing%20(USA).png',
    description: 'Start your engines for the most colorful kart racer on PlayStation.',
    year: 1999,
    publisher: 'Sony Computer Entertainment',
    developer: 'Naughty Dog',
    players: 4,
    emulator_core: 'mednafen_psx',
    playable: true,
    rom_size: 300000000,
    compatibility_status: 'verified',
    checksum: null
  },
  {
    game_id: 'SuperMetroidUSA',
    title: 'Super Metroid',
    system: 'Super Nintendo',
    system_id: 'snes',
    rom_url: 'https://archive.org/download/nointro.snes/Super%20Metroid%20%28Japan%2C%20USA%29%20%28En%2CJa%29.zip',
    cover_url: 'https://raw.githubusercontent.com/libretro/libretro-thumbnails/master/Nintendo_-_Super_Nintendo_Entertainment_System/Named_Boxarts/Super%20Metroid%20(Japan,%20USA)%20(En,Ja).png',
    artwork_url: 'https://raw.githubusercontent.com/libretro/libretro-thumbnails/master/Nintendo_-_Super_Nintendo_Entertainment_System/Named_Snaps/Super%20Metroid%20(Japan,%20USA)%20(En,Ja).png',
    description: 'The Space Pirates, led by Ridley, have stolen the last Metroid!',
    year: 1994,
    publisher: 'Nintendo',
    developer: 'Nintendo R&D1',
    players: 1,
    emulator_core: 'snes9x',
    playable: true,
    rom_size: 3145728,
    compatibility_status: 'verified',
    checksum: null
  },
  {
    game_id: 'ChronoTriggerUSA',
    title: 'Chrono Trigger',
    system: 'Super Nintendo',
    system_id: 'snes',
    rom_url: 'https://archive.org/download/nointro.snes/Chrono%20Trigger%20%28USA%29.zip',
    cover_url: 'https://raw.githubusercontent.com/libretro/libretro-thumbnails/master/Nintendo_-_Super_Nintendo_Entertainment_System/Named_Boxarts/Chrono%20Trigger%20(USA).png',
    artwork_url: 'https://raw.githubusercontent.com/libretro/libretro-thumbnails/master/Nintendo_-_Super_Nintendo_Entertainment_System/Named_Snaps/Chrono%20Trigger%20(USA).png',
    description: 'A young man travels through time to save the world from a parasitic alien.',
    year: 1995,
    publisher: 'Square',
    developer: 'Square',
    players: 1,
    emulator_core: 'snes9x',
    playable: true,
    rom_size: 4194304,
    compatibility_status: 'verified',
    checksum: null
  },
  {
    game_id: 'StreetFighterIITurboUSA',
    title: 'Street Fighter II Turbo',
    system: 'Super Nintendo',
    system_id: 'snes',
    rom_url: 'https://archive.org/download/nointro.snes/Street%20Fighter%20II%20Turbo%20-%20Hyper%20Fighting%20%28USA%29.zip',
    cover_url: 'https://raw.githubusercontent.com/libretro/libretro-thumbnails/master/Nintendo_-_Super_Nintendo_Entertainment_System/Named_Boxarts/Street%20Fighter%20II%20Turbo%20-%20Hyper%20Fighting%20(USA).png',
    artwork_url: 'https://raw.githubusercontent.com/libretro/libretro-thumbnails/master/Nintendo_-_Super_Nintendo_Entertainment_System/Named_Snaps/Street%20Fighter%20II%20Turbo%20-%20Hyper%20Fighting%20(USA).png',
    description: 'The definitive version of the fighting game that started it all.',
    year: 1993,
    publisher: 'Capcom',
    developer: 'Capcom',
    players: 2,
    emulator_core: 'snes9x',
    playable: true,
    rom_size: 2097152,
    compatibility_status: 'verified',
    checksum: null
  },
  {
    game_id: 'PokemonFireRedUSA',
    title: 'Pokemon FireRed',
    system: 'Game Boy Advance',
    system_id: 'gba',
    rom_url: 'https://archive.org/download/nointro.gba/Pokemon%20-%20FireRed%20Version%20%28USA%29.zip',
    cover_url: 'https://raw.githubusercontent.com/libretro/libretro-thumbnails/master/Nintendo_-_Game_Boy_Advance/Named_Boxarts/Pokemon%20-%20FireRed%20Version%20(USA).png',
    artwork_url: 'https://raw.githubusercontent.com/libretro/libretro-thumbnails/master/Nintendo_-_Game_Boy_Advance/Named_Snaps/Pokemon%20-%20FireRed%20Version%20(USA).png',
    description: 'Return to Kanto and catch them all in this remake of the original.',
    year: 2004,
    publisher: 'Nintendo',
    developer: 'Game Freak',
    players: 1,
    emulator_core: 'mgba',
    playable: true,
    rom_size: 16777216,
    compatibility_status: 'verified',
    checksum: null
  }
];
