import { GameObject } from './metadataNormalization';

const getUrls = (sys: string, title: string) => {
  const eSys = encodeURIComponent(sys.replace(/ /g, '_'));
  const eTitle = encodeURIComponent(title.replace(/[&*/:`<>?\|"]/g, '_'));
  return {
    cover: `https://raw.githubusercontent.com/libretro-thumbnails/${eSys}/master/Named_Boxarts/${eTitle}.png`,
    art: `https://raw.githubusercontent.com/libretro-thumbnails/${eSys}/master/Named_Snaps/${eTitle}.png`
  };
};

const NES = 'Nintendo - Nintendo Entertainment System';
const SNES = 'Nintendo - Super Nintendo Entertainment System';
const GEN = 'Sega - Mega Drive - Genesis';
const GBA = 'Nintendo - Game Boy Advance';
const N64 = 'Nintendo - Nintendo 64';
const PSX = 'Sony - PlayStation';

// Myrient Base URLs
const MYRIENT_NES = 'https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Nintendo%20Entertainment%20System%20%28Headered%29';
const MYRIENT_SNES = 'https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Super%20Nintendo%20Entertainment%20System';
const MYRIENT_GEN = 'https://myrient.erista.me/files/No-Intro/Sega%20-%20Mega%20Drive%20-%20Genesis';
const MYRIENT_GBA = 'https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Game%20Boy%20Advance';
const MYRIENT_N64 = 'https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Nintendo%2064%20%28BigEndian%29';
const MYRIENT_PSX = 'https://myrient.erista.me/files/chd/Sony%20-%20PlayStation';

export const STATIC_CORE_CATALOG: GameObject[] = [
  // NES
  {
    game_id: 'SuperMarioBros.USA',
    title: 'Super Mario Bros',
    system: 'NES',
    system_id: 'nes',
    year: 1985,
    publisher: 'Nintendo',
    developer: 'Nintendo',
    players: 2,
    rom_url: `${MYRIENT_NES}/Super%20Mario%20Bros.%20%28World%29.zip`,
    cover_url: getUrls(NES, 'Super Mario Bros. (World)').cover,
    artwork_url: getUrls(NES, 'Super Mario Bros. (World)').art,
    rom_size: 40976,
    emulator_core: 'fceumm',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'SuperMarioBros3USA',
    title: 'Super Mario Bros 3',
    system: 'NES',
    system_id: 'nes',
    year: 1988,
    publisher: 'Nintendo',
    developer: 'Nintendo',
    players: 2,
    rom_url: `${MYRIENT_NES}/Super%20Mario%20Bros.%203%20%28USA%29.zip`,
    cover_url: getUrls(NES, 'Super Mario Bros. 3 (USA)').cover,
    artwork_url: getUrls(NES, 'Super Mario Bros. 3 (USA)').art,
    rom_size: 393232,
    emulator_core: 'fceumm',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'LegendOfZeldaUSA',
    title: 'The Legend of Zelda',
    system: 'NES',
    system_id: 'nes',
    year: 1986,
    publisher: 'Nintendo',
    developer: 'Nintendo',
    players: 1,
    rom_url: `${MYRIENT_NES}/Legend%20of%20Zelda%2C%20The%20%28USA%29.zip`,
    cover_url: getUrls(NES, 'Legend of Zelda, The (USA)').cover,
    artwork_url: getUrls(NES, 'Legend of Zelda, The (USA)').art,
    rom_size: 131088,
    emulator_core: 'fceumm',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'ContraUSA',
    title: 'Contra',
    system: 'NES',
    system_id: 'nes',
    year: 1988,
    publisher: 'Konami',
    developer: 'Konami',
    players: 2,
    rom_url: `${MYRIENT_NES}/Contra%20%28USA%29.zip`,
    cover_url: getUrls(NES, 'Contra (USA)').cover,
    artwork_url: getUrls(NES, 'Contra (USA)').art,
    rom_size: 131072,
    emulator_core: 'fceumm',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'MetroidUSA',
    title: 'Metroid',
    system: 'NES',
    system_id: 'nes',
    year: 1986,
    publisher: 'Nintendo',
    developer: 'Nintendo',
    players: 1,
    rom_url: `${MYRIENT_NES}/Metroid%20%28USA%29.zip`,
    cover_url: getUrls(NES, 'Metroid (USA)').cover,
    artwork_url: getUrls(NES, 'Metroid (USA)').art,
    rom_size: 131072,
    emulator_core: 'fceumm',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'MegaMan2USA',
    title: 'Mega Man 2',
    system: 'NES',
    system_id: 'nes',
    year: 1988,
    publisher: 'Capcom',
    developer: 'Capcom',
    players: 1,
    rom_url: `${MYRIENT_NES}/Mega%20Man%202%20%28USA%29.zip`,
    cover_url: getUrls(NES, 'Mega Man 2 (USA)').cover,
    artwork_url: getUrls(NES, 'Mega Man 2 (USA)').art,
    rom_size: 262144,
    emulator_core: 'fceumm',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  // SNES
  {
    game_id: 'SuperMarioWorldUSA',
    title: 'Super Mario World',
    system: 'SNES',
    system_id: 'snes',
    year: 1990,
    publisher: 'Nintendo',
    developer: 'Nintendo',
    players: 2,
    rom_url: `${MYRIENT_SNES}/Super%20Mario%20World%20%28USA%29.zip`,
    cover_url: getUrls(SNES, 'Super Mario World (USA)').cover,
    artwork_url: getUrls(SNES, 'Super Mario World (USA)').art,
    rom_size: 524288,
    emulator_core: 'snes9x',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'LegendOfZeldaLinkToThePastUSA',
    title: 'The Legend of Zelda: A Link to the Past',
    system: 'SNES',
    system_id: 'snes',
    year: 1991,
    publisher: 'Nintendo',
    developer: 'Nintendo',
    players: 1,
    rom_url: `${MYRIENT_SNES}/Legend%20of%20Zelda%2C%20The%20-%20A%20Link%20to%20the%20Past%20%28USA%29.zip`,
    cover_url: getUrls(SNES, 'Legend of Zelda, The - A Link to the Past (USA)').cover,
    artwork_url: getUrls(SNES, 'Legend of Zelda, The - A Link to the Past (USA)').art,
    rom_size: 1048576,
    emulator_core: 'snes9x',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'SuperMetroidJU',
    title: 'Super Metroid',
    system: 'SNES',
    system_id: 'snes',
    year: 1994,
    publisher: 'Nintendo',
    developer: 'Nintendo',
    players: 1,
    rom_url: `${MYRIENT_SNES}/Super%20Metroid%20%28Japan%2C%20USA%29%20%28En%2CJa%29.zip`,
    cover_url: getUrls(SNES, 'Super Metroid (Japan, USA) (En,Ja)').cover,
    artwork_url: getUrls(SNES, 'Super Metroid (Japan, USA) (En,Ja)').art,
    rom_size: 3145728,
    emulator_core: 'snes9x',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'StreetFighterIITurboUSA',
    title: 'Street Fighter II Turbo',
    system: 'SNES',
    system_id: 'snes',
    year: 1993,
    publisher: 'Capcom',
    developer: 'Capcom',
    players: 2,
    rom_url: `${MYRIENT_SNES}/Street%20Fighter%20II%20Turbo%20%28USA%29.zip`,
    cover_url: getUrls(SNES, 'Street Fighter II Turbo (USA)').cover,
    artwork_url: getUrls(SNES, 'Street Fighter II Turbo (USA)').art,
    rom_size: 2097152,
    emulator_core: 'snes9x',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'DonkeyKongCountryUSA',
    title: 'Donkey Kong Country',
    system: 'SNES',
    system_id: 'snes',
    year: 1994,
    publisher: 'Nintendo',
    developer: 'Rare',
    players: 2,
    rom_url: `${MYRIENT_SNES}/Donkey%20Kong%20Country%20%28USA%29.zip`,
    cover_url: getUrls(SNES, 'Donkey Kong Country (USA)').cover,
    artwork_url: getUrls(SNES, 'Donkey Kong Country (USA)').art,
    rom_size: 3145728,
    emulator_core: 'snes9x',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'ChronoTriggerUSA',
    title: 'Chrono Trigger',
    system: 'SNES',
    system_id: 'snes',
    year: 1995,
    publisher: 'Square',
    developer: 'Square',
    players: 1,
    rom_url: `${MYRIENT_SNES}/Chrono%20Trigger%20%28USA%29.zip`,
    cover_url: getUrls(SNES, 'Chrono Trigger (USA)').cover,
    artwork_url: getUrls(SNES, 'Chrono Trigger (USA)').art,
    rom_size: 4194304,
    emulator_core: 'snes9x',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  // GENESIS
  {
    game_id: 'SonicTheHedgehogUSA',
    title: 'Sonic the Hedgehog',
    system: 'Genesis',
    system_id: 'sega_genesis',
    year: 1991,
    publisher: 'Sega',
    developer: 'Sonic Team',
    players: 1,
    rom_url: `${MYRIENT_GEN}/Sonic%20The%20Hedgehog%20%28USA%2C%20Europe%29.zip`,
    cover_url: getUrls(GEN, 'Sonic the Hedgehog (USA, Europe)').cover,
    artwork_url: getUrls(GEN, 'Sonic the Hedgehog (USA, Europe)').art,
    rom_size: 524288,
    emulator_core: 'genesis_plus_gx',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'SonicTheHedgehog2USA',
    title: 'Sonic the Hedgehog 2',
    system: 'Genesis',
    system_id: 'sega_genesis',
    year: 1992,
    publisher: 'Sega',
    developer: 'Sonic Team',
    players: 2,
    rom_url: `${MYRIENT_GEN}/Sonic%20The%20Hedgehog%202%20%28World%29.zip`,
    cover_url: getUrls(GEN, 'Sonic the Hedgehog 2 (World)').cover,
    artwork_url: getUrls(GEN, 'Sonic the Hedgehog 2 (World)').art,
    rom_size: 1048576,
    emulator_core: 'genesis_plus_gx',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'StreetsOfRage2USA',
    title: 'Streets of Rage 2',
    system: 'Genesis',
    system_id: 'sega_genesis',
    year: 1992,
    publisher: 'Sega',
    developer: 'Sega',
    players: 2,
    rom_url: `${MYRIENT_GEN}/Streets%20of%20Rage%202%20%28USA%29.zip`,
    cover_url: getUrls(GEN, 'Streets of Rage 2 (USA)').cover,
    artwork_url: getUrls(GEN, 'Streets of Rage 2 (USA)').art,
    rom_size: 2097152,
    emulator_core: 'genesis_plus_gx',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'MortalKombatIIUSA',
    title: 'Mortal Kombat II',
    system: 'Genesis',
    system_id: 'sega_genesis',
    year: 1993,
    publisher: 'Acclaim',
    developer: 'Midway',
    players: 2,
    rom_url: `${MYRIENT_GEN}/Mortal%20Kombat%20II%20%28World%29.zip`,
    cover_url: getUrls(GEN, 'Mortal Kombat II (World)').cover,
    artwork_url: getUrls(GEN, 'Mortal Kombat II (World)').art,
    rom_size: 3145728,
    emulator_core: 'genesis_plus_gx',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  // GBA
  {
    game_id: 'PokemonFireRedUSA',
    title: 'Pokemon FireRed',
    system: 'GBA',
    system_id: 'gba',
    year: 2004,
    publisher: 'Nintendo',
    developer: 'Game Freak',
    players: 1,
    rom_url: `${MYRIENT_GBA}/Pokemon%20-%20FireRed%20Version%20%28USA%2C%20Europe%29.zip`,
    cover_url: getUrls(GBA, 'Pokemon - FireRed Version (USA)').cover,
    artwork_url: getUrls(GBA, 'Pokemon - FireRed Version (USA)').art,
    rom_size: 16777216,
    emulator_core: 'mgba',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'PokemonEmeraldUSA',
    title: 'Pokemon Emerald',
    system: 'GBA',
    system_id: 'gba',
    year: 2005,
    publisher: 'Nintendo',
    developer: 'Game Freak',
    players: 1,
    rom_url: `${MYRIENT_GBA}/Pokemon%20-%20Emerald%20Version%20%28USA%2C%20Europe%29.zip`,
    cover_url: getUrls(GBA, 'Pokemon - Emerald Version (USA, Europe)').cover,
    artwork_url: getUrls(GBA, 'Pokemon - Emerald Version (USA, Europe)').art,
    rom_size: 16777216,
    emulator_core: 'mgba',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'MetroidFusionUSA',
    title: 'Metroid Fusion',
    system: 'GBA',
    system_id: 'gba',
    year: 2002,
    publisher: 'Nintendo',
    developer: 'Nintendo',
    players: 1,
    rom_url: `${MYRIENT_GBA}/Metroid%20Fusion%20%28USA%29.zip`,
    cover_url: getUrls(GBA, 'Metroid Fusion (USA)').cover,
    artwork_url: getUrls(GBA, 'Metroid Fusion (USA)').art,
    rom_size: 8388608,
    emulator_core: 'mgba',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'LegendOfZeldaMinishCapUSA',
    title: 'The Legend of Zelda: The Minish Cap',
    system: 'GBA',
    system_id: 'gba',
    year: 2004,
    publisher: 'Nintendo',
    developer: 'Capcom',
    players: 1,
    rom_url: `${MYRIENT_GBA}/Legend%20of%20Zelda%2C%20The%20-%20The%20Minish%20Cap%20%28USA%29.zip`,
    cover_url: getUrls(GBA, 'Legend of Zelda, The - The Minish Cap (USA)').cover,
    artwork_url: getUrls(GBA, 'Legend of Zelda, The - The Minish Cap (USA)').art,
    rom_size: 8388608,
    emulator_core: 'mgba',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'MarioKartSuperCircuitUSA',
    title: 'Mario Kart: Super Circuit',
    system: 'GBA',
    system_id: 'gba',
    year: 2001,
    publisher: 'Nintendo',
    developer: 'Intelligent Systems',
    players: 4,
    rom_url: `${MYRIENT_GBA}/Mario%20Kart%20-%20Super%20Circuit%20%28USA%29.zip`,
    cover_url: getUrls(GBA, 'Mario Kart - Super Circuit (USA)').cover,
    artwork_url: getUrls(GBA, 'Mario Kart - Super Circuit (USA)').art,
    rom_size: 4194304,
    emulator_core: 'mgba',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'CastlevaniaAriaOfSorrowUSA',
    title: 'Castlevania: Aria of Sorrow',
    system: 'GBA',
    system_id: 'gba',
    year: 2003,
    publisher: 'Konami',
    developer: 'Konami',
    players: 1,
    rom_url: `${MYRIENT_GBA}/Castlevania%20-%20Aria%20of%20Sorrow%20%28USA%29.zip`,
    cover_url: getUrls(GBA, 'Castlevania - Aria of Sorrow (USA)').cover,
    artwork_url: getUrls(GBA, 'Castlevania - Aria of Sorrow (USA)').art,
    rom_size: 8388608,
    emulator_core: 'mgba',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  // N64
  {
    game_id: 'SuperMario64USA',
    title: 'Super Mario 64',
    system: 'N64',
    system_id: 'n64',
    year: 1996,
    publisher: 'Nintendo',
    developer: 'Nintendo',
    players: 1,
    rom_url: `${MYRIENT_N64}/Super%20Mario%2064%20%28USA%29.zip`,
    cover_url: getUrls(N64, 'Super Mario 64 (USA)').cover,
    artwork_url: getUrls(N64, 'Super Mario 64 (USA)').art,
    rom_size: 8388608,
    emulator_core: 'mupen64plus_next',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'MarioKart64USA',
    title: 'Mario Kart 64',
    system: 'N64',
    system_id: 'n64',
    year: 1997,
    publisher: 'Nintendo',
    developer: 'Nintendo',
    players: 4,
    rom_url: `${MYRIENT_N64}/Mario%20Kart%2064%20%28USA%29.zip`,
    cover_url: getUrls(N64, 'Mario Kart 64 (USA)').cover,
    artwork_url: getUrls(N64, 'Mario Kart 64 (USA)').art,
    rom_size: 12582912,
    emulator_core: 'mupen64plus_next',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'LegendOfZeldaOcarinaOfTimeUSA',
    title: 'The Legend of Zelda: Ocarina of Time',
    system: 'N64',
    system_id: 'n64',
    year: 1998,
    publisher: 'Nintendo',
    developer: 'Nintendo',
    players: 1,
    rom_url: `${MYRIENT_N64}/Legend%20of%20Zelda%2C%20The%20-%20Ocarina%20of%20Time%20%28USA%29.zip`,
    cover_url: getUrls(N64, 'Legend of Zelda, The - Ocarina of Time (USA)').cover,
    artwork_url: getUrls(N64, 'Legend of Zelda, The - Ocarina of Time (USA)').art,
    rom_size: 33554432,
    emulator_core: 'mupen64plus_next',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'SuperSmashBrosUSA',
    title: 'Super Smash Bros',
    system: 'N64',
    system_id: 'n64',
    year: 1999,
    publisher: 'Nintendo',
    developer: 'HAL Laboratory',
    players: 4,
    rom_url: `${MYRIENT_N64}/Super%20Smash%20Bros.%20%28USA%29.zip`,
    cover_url: getUrls(N64, 'Super Smash Bros. (USA)').cover,
    artwork_url: getUrls(N64, 'Super Smash Bros. (USA)').art,
    rom_size: 16777216,
    emulator_core: 'mupen64plus_next',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  // PSX
  {
    game_id: 'CrashBandicootUSA',
    title: 'Crash Bandicoot',
    system: 'PS1',
    system_id: 'psx',
    year: 1996,
    publisher: 'Sony',
    developer: 'Naughty Dog',
    players: 1,
    rom_url: `${MYRIENT_PSX}/Crash%20Bandicoot%20%28USA%29.chd`,
    cover_url: getUrls(PSX, 'Crash Bandicoot (USA)').cover,
    artwork_url: getUrls(PSX, 'Crash Bandicoot (USA)').art,
    rom_size: 500000000,
    emulator_core: 'pcsx_rearmed',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'Tekken3USA',
    title: 'Tekken 3',
    system: 'PS1',
    system_id: 'psx',
    year: 1998,
    publisher: 'Namco',
    developer: 'Namco',
    players: 2,
    rom_url: `${MYRIENT_PSX}/Tekken%203%20%28USA%29.chd`,
    cover_url: getUrls(PSX, 'Tekken 3 (USA)').cover,
    artwork_url: getUrls(PSX, 'Tekken 3 (USA)').art,
    rom_size: 600000000,
    emulator_core: 'pcsx_rearmed',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'MetalGearSolidUSA',
    title: 'Metal Gear Solid',
    system: 'PS1',
    system_id: 'psx',
    year: 1998,
    publisher: 'Konami',
    developer: 'Konami',
    players: 1,
    rom_url: `${MYRIENT_PSX}/Metal%20Gear%20Solid%20%28USA%29%20%28Disc%201%29%20%28v1.1%29.chd`,
    cover_url: getUrls(PSX, 'Metal Gear Solid (USA) (Disc 1)').cover,
    artwork_url: getUrls(PSX, 'Metal Gear Solid (USA) (Disc 1)').art,
    rom_size: 600000000,
    emulator_core: 'pcsx_rearmed',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'FinalFantasyVIIUSA',
    title: 'Final Fantasy VII',
    system: 'PS1',
    system_id: 'psx',
    year: 1997,
    publisher: 'Square',
    developer: 'Square',
    players: 1,
    rom_url: `${MYRIENT_PSX}/Final%20Fantasy%20VII%20%28USA%29%20%28Disc%201%29.chd`,
    cover_url: getUrls(PSX, 'Final Fantasy VII (USA) (Disc 1)').cover,
    artwork_url: getUrls(PSX, 'Final Fantasy VII (USA) (Disc 1)').art,
    rom_size: 600000000,
    emulator_core: 'pcsx_rearmed',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'CastlevaniaSOTNUSA',
    title: 'Castlevania: Symphony of the Night',
    system: 'PS1',
    system_id: 'psx',
    year: 1997,
    publisher: 'Konami',
    developer: 'Konami',
    players: 1,
    rom_url: `${MYRIENT_PSX}/Castlevania%20-%20Symphony%20of%20the%20Night%20%28USA%29.chd`,
    cover_url: getUrls(PSX, 'Castlevania - Symphony of the Night (USA)').cover,
    artwork_url: getUrls(PSX, 'Castlevania - Symphony of the Night (USA)').art,
    rom_size: 400000000,
    emulator_core: 'pcsx_rearmed',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  // NEW ADDITIONS - NES
  {
    game_id: 'MikeTysonsPunchOutUSA',
    title: "Mike Tyson's Punch-Out!!",
    system: 'NES',
    system_id: 'nes',
    year: 1987,
    publisher: 'Nintendo',
    developer: 'Nintendo',
    players: 1,
    rom_url: `${MYRIENT_NES}/Mike%20Tyson%27s%20Punch-Out%21%21%20%28USA%29.zip`,
    cover_url: getUrls(NES, "Mike Tyson's Punch-Out!! (USA)").cover,
    artwork_url: getUrls(NES, "Mike Tyson's Punch-Out!! (USA)").art,
    rom_size: 262144,
    emulator_core: 'fceumm',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'KirbysAdventureUSA',
    title: "Kirby's Adventure",
    system: 'NES',
    system_id: 'nes',
    year: 1993,
    publisher: 'Nintendo',
    developer: 'HAL Laboratory',
    players: 1,
    rom_url: `${MYRIENT_NES}/Kirby%27s%20Adventure%20%28USA%29.zip`,
    cover_url: getUrls(NES, "Kirby's Adventure (USA)").cover,
    artwork_url: getUrls(NES, "Kirby's Adventure (USA)").art,
    rom_size: 786432,
    emulator_core: 'fceumm',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'NinjaGaidenUSA',
    title: 'Ninja Gaiden',
    system: 'NES',
    system_id: 'nes',
    year: 1988,
    publisher: 'Tecmo',
    developer: 'Tecmo',
    players: 1,
    rom_url: `${MYRIENT_NES}/Ninja%20Gaiden%20%28USA%29.zip`,
    cover_url: getUrls(NES, 'Ninja Gaiden (USA)').cover,
    artwork_url: getUrls(NES, 'Ninja Gaiden (USA)').art,
    rom_size: 262144,
    emulator_core: 'fceumm',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  // NEW ADDITIONS - SNES
  {
    game_id: 'EarthBoundUSA',
    title: 'EarthBound',
    system: 'SNES',
    system_id: 'snes',
    year: 1994,
    publisher: 'Nintendo',
    developer: 'Ape / HAL',
    players: 1,
    rom_url: `${MYRIENT_SNES}/EarthBound%20%28USA%29.zip`,
    cover_url: getUrls(SNES, 'EarthBound (USA)').cover,
    artwork_url: getUrls(SNES, 'EarthBound (USA)').art,
    rom_size: 3145728,
    emulator_core: 'snes9x',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'SuperMarioKartUSA',
    title: 'Super Mario Kart',
    system: 'SNES',
    system_id: 'snes',
    year: 1992,
    publisher: 'Nintendo',
    developer: 'Nintendo',
    players: 2,
    rom_url: `${MYRIENT_SNES}/Super%20Mario%20Kart%20%28USA%29.zip`,
    cover_url: getUrls(SNES, 'Super Mario Kart (USA)').cover,
    artwork_url: getUrls(SNES, 'Super Mario Kart (USA)').art,
    rom_size: 524288,
    emulator_core: 'snes9x',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'StarFoxUSA',
    title: 'Star Fox',
    system: 'SNES',
    system_id: 'snes',
    year: 1993,
    publisher: 'Nintendo',
    developer: 'Nintendo',
    players: 1,
    rom_url: `${MYRIENT_SNES}/Star%20Fox%20%28USA%29.zip`,
    cover_url: getUrls(SNES, 'Star Fox (USA)').cover,
    artwork_url: getUrls(SNES, 'Star Fox (USA)').art,
    rom_size: 1048576,
    emulator_core: 'snes9x',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  // NEW ADDITIONS - GENESIS
  {
    game_id: 'SonicTheHedgehog3USA',
    title: 'Sonic the Hedgehog 3',
    system: 'Genesis',
    system_id: 'sega_genesis',
    year: 1994,
    publisher: 'Sega',
    developer: 'Sonic Team',
    players: 2,
    rom_url: `${MYRIENT_GEN}/Sonic%20The%20Hedgehog%203%20%28USA%29.zip`,
    cover_url: getUrls(GEN, 'Sonic the Hedgehog 3 (USA)').cover,
    artwork_url: getUrls(GEN, 'Sonic the Hedgehog 3 (USA)').art,
    rom_size: 2097152,
    emulator_core: 'genesis_plus_gx',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'GoldenAxeWorld',
    title: 'Golden Axe',
    system: 'Genesis',
    system_id: 'sega_genesis',
    year: 1989,
    publisher: 'Sega',
    developer: 'Sega',
    players: 2,
    rom_url: `${MYRIENT_GEN}/Golden%20Axe%20%28World%29.zip`,
    cover_url: getUrls(GEN, 'Golden Axe (World)').cover,
    artwork_url: getUrls(GEN, 'Golden Axe (World)').art,
    rom_size: 524288,
    emulator_core: 'genesis_plus_gx',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'GunstarHeroesUSA',
    title: 'Gunstar Heroes',
    system: 'Genesis',
    system_id: 'sega_genesis',
    year: 1993,
    publisher: 'Sega',
    developer: 'Treasure',
    players: 2,
    rom_url: `${MYRIENT_GEN}/Gunstar%20Heroes%20%28USA%29.zip`,
    cover_url: getUrls(GEN, 'Gunstar Heroes (USA)').cover,
    artwork_url: getUrls(GEN, 'Gunstar Heroes (USA)').art,
    rom_size: 1048576,
    emulator_core: 'genesis_plus_gx',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  // NEW ADDITIONS - GBA
  {
    game_id: 'PokemonRubyUSA',
    title: 'Pokemon Ruby',
    system: 'GBA',
    system_id: 'gba',
    year: 2002,
    publisher: 'Nintendo',
    developer: 'Game Freak',
    players: 1,
    rom_url: `${MYRIENT_GBA}/Pokemon%20-%20Ruby%20Version%20%28USA%2C%20Europe%29.zip`,
    cover_url: getUrls(GBA, 'Pokemon - Ruby Version (USA)').cover,
    artwork_url: getUrls(GBA, 'Pokemon - Ruby Version (USA)').art,
    rom_size: 16777216,
    emulator_core: 'mgba',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'AdvanceWarsUSA',
    title: 'Advance Wars',
    system: 'GBA',
    system_id: 'gba',
    year: 2001,
    publisher: 'Nintendo',
    developer: 'Intelligent Systems',
    players: 1,
    rom_url: `${MYRIENT_GBA}/Advance%20Wars%20%28USA%29.zip`,
    cover_url: getUrls(GBA, 'Advance Wars (USA)').cover,
    artwork_url: getUrls(GBA, 'Advance Wars (USA)').art,
    rom_size: 8388608,
    emulator_core: 'mgba',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'GoldenSunUSA',
    title: 'Golden Sun',
    system: 'GBA',
    system_id: 'gba',
    year: 2001,
    publisher: 'Nintendo',
    developer: 'Camelot',
    players: 1,
    rom_url: `${MYRIENT_GBA}/Golden%20Sun%20%28USA%2C%20Europe%29.zip`,
    cover_url: getUrls(GBA, 'Golden Sun (USA)').cover,
    artwork_url: getUrls(GBA, 'Golden Sun (USA)').art,
    rom_size: 8388608,
    emulator_core: 'mgba',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  // NEW ADDITIONS - N64
  {
    game_id: 'GoldenEye007USA',
    title: 'GoldenEye 007',
    system: 'N64',
    system_id: 'n64',
    year: 1997,
    publisher: 'Nintendo',
    developer: 'Rare',
    players: 4,
    rom_url: `${MYRIENT_N64}/GoldenEye%20007%20%28USA%29.zip`,
    cover_url: getUrls(N64, 'GoldenEye 007 (USA)').cover,
    artwork_url: getUrls(N64, 'GoldenEye 007 (USA)').art,
    rom_size: 12582912,
    emulator_core: 'mupen64plus_next',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'StarFox64USA',
    title: 'Star Fox 64',
    system: 'N64',
    system_id: 'n64',
    year: 1997,
    publisher: 'Nintendo',
    developer: 'Nintendo',
    players: 4,
    rom_url: `${MYRIENT_N64}/Star%20Fox%2064%20%28USA%29.zip`,
    cover_url: getUrls(N64, 'Star Fox 64 (USA)').cover,
    artwork_url: getUrls(N64, 'Star Fox 64 (USA)').art,
    rom_size: 12582912,
    emulator_core: 'mupen64plus_next',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  // NEW ADDITIONS - PSX
  {
    game_id: 'ResidentEvil2USA',
    title: 'Resident Evil 2',
    system: 'PS1',
    system_id: 'psx',
    year: 1998,
    publisher: 'Capcom',
    developer: 'Capcom',
    players: 1,
    rom_url: `${MYRIENT_PSX}/Resident%20Evil%202%20%28USA%29%20%28Disc%201%29%20%28Leon%29.chd`,
    cover_url: getUrls(PSX, 'Resident Evil 2 (USA) (Disc 1) (Leon)').cover,
    artwork_url: getUrls(PSX, 'Resident Evil 2 (USA) (Disc 1) (Leon)').art,
    rom_size: 500000000,
    emulator_core: 'pcsx_rearmed',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'SpyroTheDragonUSA',
    title: 'Spyro the Dragon',
    system: 'PS1',
    system_id: 'psx',
    year: 1998,
    publisher: 'Sony',
    developer: 'Insomniac Games',
    players: 1,
    rom_url: `${MYRIENT_PSX}/Spyro%20the%20Dragon%20%28USA%29.chd`,
    cover_url: getUrls(PSX, 'Spyro the Dragon (USA)').cover,
    artwork_url: getUrls(PSX, 'Spyro the Dragon (USA)').art,
    rom_size: 400000000,
    emulator_core: 'pcsx_rearmed',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  // EXPANSION BATCH 2 - NES
  {
    game_id: 'CastlevaniaIIIUSA',
    title: "Castlevania III: Dracula's Curse",
    system: 'NES',
    system_id: 'nes',
    year: 1990,
    publisher: 'Konami',
    developer: 'Konami',
    players: 1,
    rom_url: `${MYRIENT_NES}/Castlevania%20III%20-%20Dracula%27s%20Curse%20%28USA%29.zip`,
    cover_url: getUrls(NES, "Castlevania III - Dracula's Curse (USA)").cover,
    artwork_url: getUrls(NES, "Castlevania III - Dracula's Curse (USA)").art,
    rom_size: 393216,
    emulator_core: 'fceumm',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'DoubleDragonIIUSA',
    title: 'Double Dragon II: The Revenge',
    system: 'NES',
    system_id: 'nes',
    year: 1990,
    publisher: 'Acclaim',
    developer: 'Technos',
    players: 2,
    rom_url: `${MYRIENT_NES}/Double%20Dragon%20II%20-%20The%20Revenge%20%28USA%29.zip`,
    cover_url: getUrls(NES, 'Double Dragon II - The Revenge (USA)').cover,
    artwork_url: getUrls(NES, 'Double Dragon II - The Revenge (USA)').art,
    rom_size: 262144,
    emulator_core: 'fceumm',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'DuckTalesUSA',
    title: 'DuckTales',
    system: 'NES',
    system_id: 'nes',
    year: 1989,
    publisher: 'Capcom',
    developer: 'Capcom',
    players: 1,
    rom_url: `${MYRIENT_NES}/DuckTales%20%28USA%29.zip`,
    cover_url: getUrls(NES, 'DuckTales (USA)').cover,
    artwork_url: getUrls(NES, 'DuckTales (USA)').art,
    rom_size: 131072,
    emulator_core: 'fceumm',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  // EXPANSION BATCH 2 - SNES
  {
    game_id: 'MegaManXUSA',
    title: 'Mega Man X',
    system: 'SNES',
    system_id: 'snes',
    year: 1993,
    publisher: 'Capcom',
    developer: 'Capcom',
    players: 1,
    rom_url: `${MYRIENT_SNES}/Mega%20Man%20X%20%28USA%29.zip`,
    cover_url: getUrls(SNES, 'Mega Man X (USA)').cover,
    artwork_url: getUrls(SNES, 'Mega Man X (USA)').art,
    rom_size: 1572864,
    emulator_core: 'snes9x',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'FinalFantasyIIIUSA',
    title: 'Final Fantasy III',
    system: 'SNES',
    system_id: 'snes',
    year: 1994,
    publisher: 'Square',
    developer: 'Square',
    players: 2,
    rom_url: `${MYRIENT_SNES}/Final%20Fantasy%20III%20%28USA%29.zip`,
    cover_url: getUrls(SNES, 'Final Fantasy III (USA)').cover,
    artwork_url: getUrls(SNES, 'Final Fantasy III (USA)').art,
    rom_size: 3145728,
    emulator_core: 'snes9x',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'SecretOfManaUSA',
    title: 'Secret of Mana',
    system: 'SNES',
    system_id: 'snes',
    year: 1993,
    publisher: 'Square',
    developer: 'Square',
    players: 3,
    rom_url: `${MYRIENT_SNES}/Secret%20of%20Mana%20%28USA%29.zip`,
    cover_url: getUrls(SNES, 'Secret of Mana (USA)').cover,
    artwork_url: getUrls(SNES, 'Secret of Mana (USA)').art,
    rom_size: 2097152,
    emulator_core: 'snes9x',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  // EXPANSION BATCH 2 - GENESIS
  {
    game_id: 'ShinobiIIIUSA',
    title: 'Shinobi III: Return of the Ninja Master',
    system: 'Genesis',
    system_id: 'sega_genesis',
    year: 1993,
    publisher: 'Sega',
    developer: 'Sega',
    players: 1,
    rom_url: `${MYRIENT_GEN}/Shinobi%20III%20-%20Return%20of%20the%20Ninja%20Master%20%28USA%29.zip`,
    cover_url: getUrls(GEN, 'Shinobi III - Return of the Ninja Master (USA)').cover,
    artwork_url: getUrls(GEN, 'Shinobi III - Return of the Ninja Master (USA)').art,
    rom_size: 1048576,
    emulator_core: 'genesis_plus_gx',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'PhantasyStarIVUSA',
    title: 'Phantasy Star IV',
    system: 'Genesis',
    system_id: 'sega_genesis',
    year: 1993,
    publisher: 'Sega',
    developer: 'Sega',
    players: 1,
    rom_url: `${MYRIENT_GEN}/Phantasy%20Star%20IV%20%28USA%29.zip`,
    cover_url: getUrls(GEN, 'Phantasy Star IV (USA)').cover,
    artwork_url: getUrls(GEN, 'Phantasy Star IV (USA)').art,
    rom_size: 3145728,
    emulator_core: 'genesis_plus_gx',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'ComixZoneUSA',
    title: 'Comix Zone',
    system: 'Genesis',
    system_id: 'sega_genesis',
    year: 1995,
    publisher: 'Sega',
    developer: 'Sega',
    players: 1,
    rom_url: `${MYRIENT_GEN}/Comix%20Zone%20%28USA%29.zip`,
    cover_url: getUrls(GEN, 'Comix Zone (USA)').cover,
    artwork_url: getUrls(GEN, 'Comix Zone (USA)').art,
    rom_size: 2097152,
    emulator_core: 'genesis_plus_gx',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  // EXPANSION BATCH 2 - GBA
  {
    game_id: 'CastlevaniaCircleOfTheMoonUSA',
    title: 'Castlevania: Circle of the Moon',
    system: 'GBA',
    system_id: 'gba',
    year: 2001,
    publisher: 'Konami',
    developer: 'Konami',
    players: 1,
    rom_url: `${MYRIENT_GBA}/Castlevania%20-%20Circle%20of%20the%20Moon%20%28USA%29.zip`,
    cover_url: getUrls(GBA, 'Castlevania - Circle of the Moon (USA)').cover,
    artwork_url: getUrls(GBA, 'Castlevania - Circle of the Moon (USA)').art,
    rom_size: 8388608,
    emulator_core: 'mgba',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'MetroidZeroMissionUSA',
    title: 'Metroid: Zero Mission',
    system: 'GBA',
    system_id: 'gba',
    year: 2004,
    publisher: 'Nintendo',
    developer: 'Nintendo',
    players: 1,
    rom_url: `${MYRIENT_GBA}/Metroid%20-%20Zero%20Mission%20%28USA%29.zip`,
    cover_url: getUrls(GBA, 'Metroid - Zero Mission (USA)').cover,
    artwork_url: getUrls(GBA, 'Metroid - Zero Mission (USA)').art,
    rom_size: 8388608,
    emulator_core: 'mgba',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'MarioAndLuigiSuperstarSagaUSA',
    title: 'Mario & Luigi: Superstar Saga',
    system: 'GBA',
    system_id: 'gba',
    year: 2003,
    publisher: 'Nintendo',
    developer: 'AlphaDream',
    players: 1,
    rom_url: `${MYRIENT_GBA}/Mario%20%26%20Luigi%20-%20Superstar%20Saga%20%28USA%29.zip`,
    cover_url: getUrls(GBA, 'Mario & Luigi - Superstar Saga (USA)').cover,
    artwork_url: getUrls(GBA, 'Mario & Luigi - Superstar Saga (USA)').art,
    rom_size: 16777216,
    emulator_core: 'mgba',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  // EXPANSION BATCH 2 - N64
  {
    game_id: 'BanjoKazooieUSA',
    title: 'Banjo-Kazooie',
    system: 'N64',
    system_id: 'n64',
    year: 1998,
    publisher: 'Nintendo',
    developer: 'Rare',
    players: 1,
    rom_url: `${MYRIENT_N64}/Banjo-Kazooie%20%28USA%29.zip`,
    cover_url: getUrls(N64, 'Banjo-Kazooie (USA)').cover,
    artwork_url: getUrls(N64, 'Banjo-Kazooie (USA)').art,
    rom_size: 16777216,
    emulator_core: 'mupen64plus_next',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'PerfectDarkUSA',
    title: 'Perfect Dark',
    system: 'N64',
    system_id: 'n64',
    year: 2000,
    publisher: 'Nintendo',
    developer: 'Rare',
    players: 4,
    rom_url: `${MYRIENT_N64}/Perfect%20Dark%20%28USA%29.zip`,
    cover_url: getUrls(N64, 'Perfect Dark (USA)').cover,
    artwork_url: getUrls(N64, 'Perfect Dark (USA)').art,
    rom_size: 33554432,
    emulator_core: 'mupen64plus_next',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  // EXPANSION BATCH 2 - PSX
  {
    game_id: 'GranTurismo2USA',
    title: 'Gran Turismo 2',
    system: 'PS1',
    system_id: 'psx',
    year: 1999,
    publisher: 'Sony',
    developer: 'Polyphony Digital',
    players: 2,
    rom_url: `${MYRIENT_PSX}/Gran%20Turismo%202%20%28USA%29%20%28Arcade%20Mode%29%20%28v1.1%29.chd`,
    cover_url: getUrls(PSX, 'Gran Turismo 2 (USA) (Arcade Mode)').cover,
    artwork_url: getUrls(PSX, 'Gran Turismo 2 (USA) (Arcade Mode)').art,
    rom_size: 600000000,
    emulator_core: 'pcsx_rearmed',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'TonyHawkProSkater2USA',
    title: "Tony Hawk's Pro Skater 2",
    system: 'PS1',
    system_id: 'psx',
    year: 2000,
    publisher: 'Activision',
    developer: 'Neversoft',
    players: 2,
    rom_url: `${MYRIENT_PSX}/Tony%20Hawk%27s%20Pro%20Skater%202%20%28USA%29.chd`,
    cover_url: getUrls(PSX, "Tony Hawk's Pro Skater 2 (USA)").cover,
    artwork_url: getUrls(PSX, "Tony Hawk's Pro Skater 2 (USA)").art,
    rom_size: 450000000,
    emulator_core: 'pcsx_rearmed',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  // EXPANSION BATCH 3 - SNES OVERDRIVE (Pushing > 20)
  {
    game_id: 'SuperMarioRPGUSA',
    title: 'Super Mario RPG: Legend of the Seven Stars',
    system: 'SNES',
    system_id: 'snes',
    year: 1996,
    publisher: 'Nintendo',
    developer: 'Square',
    players: 1,
    rom_url: `${MYRIENT_SNES}/Super%20Mario%20RPG%20-%20Legend%20of%20the%20Seven%20Stars%20%28USA%29.zip`,
    cover_url: getUrls(SNES, 'Super Mario RPG - Legend of the Seven Stars (USA)').cover,
    artwork_url: getUrls(SNES, 'Super Mario RPG - Legend of the Seven Stars (USA)').art,
    rom_size: 4194304,
    emulator_core: 'snes9x',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'FinalFantasyIIIUSA',
    title: 'Final Fantasy III',
    system: 'SNES',
    system_id: 'snes',
    year: 1994,
    publisher: 'Square',
    developer: 'Square',
    players: 2,
    rom_url: `${MYRIENT_SNES}/Final%20Fantasy%20III%20%28USA%29.zip`,
    cover_url: getUrls(SNES, 'Final Fantasy III (USA)').cover,
    artwork_url: getUrls(SNES, 'Final Fantasy III (USA)').art,
    rom_size: 3145728,
    emulator_core: 'snes9x',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'SecretOfManaUSA',
    title: 'Secret of Mana',
    system: 'SNES',
    system_id: 'snes',
    year: 1993,
    publisher: 'Square',
    developer: 'Square',
    players: 3,
    rom_url: `${MYRIENT_SNES}/Secret%20of%20Mana%20%28USA%29.zip`,
    cover_url: getUrls(SNES, 'Secret of Mana (USA)').cover,
    artwork_url: getUrls(SNES, 'Secret of Mana (USA)').art,
    rom_size: 2097152,
    emulator_core: 'snes9x',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'MegaManXUSA',
    title: 'Mega Man X',
    system: 'SNES',
    system_id: 'snes',
    year: 1993,
    publisher: 'Capcom',
    developer: 'Capcom',
    players: 1,
    rom_url: `${MYRIENT_SNES}/Mega%20Man%20X%20%28USA%29.zip`,
    cover_url: getUrls(SNES, 'Mega Man X (USA)').cover,
    artwork_url: getUrls(SNES, 'Mega Man X (USA)').art,
    rom_size: 1572864,
    emulator_core: 'snes9x',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'DonkeyKongCountry2USA',
    title: "Donkey Kong Country 2: Diddy's Kong Quest",
    system: 'SNES',
    system_id: 'snes',
    year: 1995,
    publisher: 'Nintendo',
    developer: 'Rare',
    players: 2,
    rom_url: `${MYRIENT_SNES}/Donkey%20Kong%20Country%202%20-%20Diddy%27s%20Kong%20Quest%20%28USA%29%20%28En%2CFr%29.zip`,
    cover_url: getUrls(SNES, "Donkey Kong Country 2 - Diddy's Kong Quest (USA) (En,Fr)").cover,
    artwork_url: getUrls(SNES, "Donkey Kong Country 2 - Diddy's Kong Quest (USA) (En,Fr)").art,
    rom_size: 4194304,
    emulator_core: 'snes9x',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'SuperCastlevaniaIVUSA',
    title: 'Super Castlevania IV',
    system: 'SNES',
    system_id: 'snes',
    year: 1991,
    publisher: 'Konami',
    developer: 'Konami',
    players: 1,
    rom_url: `${MYRIENT_SNES}/Super%20Castlevania%20IV%20%28USA%29.zip`,
    cover_url: getUrls(SNES, 'Super Castlevania IV (USA)').cover,
    artwork_url: getUrls(SNES, 'Super Castlevania IV (USA)').art,
    rom_size: 1048576,
    emulator_core: 'snes9x',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'FZeroUSA',
    title: 'F-Zero',
    system: 'SNES',
    system_id: 'snes',
    year: 1990,
    publisher: 'Nintendo',
    developer: 'Nintendo',
    players: 1,
    rom_url: `${MYRIENT_SNES}/F-Zero%20%28USA%29.zip`,
    cover_url: getUrls(SNES, 'F-Zero (USA)').cover,
    artwork_url: getUrls(SNES, 'F-Zero (USA)').art,
    rom_size: 524288,
    emulator_core: 'snes9x',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'ContraIIIUSA',
    title: 'Contra III: The Alien Wars',
    system: 'SNES',
    system_id: 'snes',
    year: 1992,
    publisher: 'Konami',
    developer: 'Konami',
    players: 2,
    rom_url: `${MYRIENT_SNES}/Contra%20III%20-%20The%20Alien%20Wars%20%28USA%29.zip`,
    cover_url: getUrls(SNES, 'Contra III - The Alien Wars (USA)').cover,
    artwork_url: getUrls(SNES, 'Contra III - The Alien Wars (USA)').art,
    rom_size: 1048576,
    emulator_core: 'snes9x',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'TMNTIVUSA',
    title: 'Teenage Mutant Ninja Turtles IV: Turtles in Time',
    system: 'SNES',
    system_id: 'snes',
    year: 1992,
    publisher: 'Konami',
    developer: 'Konami',
    players: 2,
    rom_url: `${MYRIENT_SNES}/Teenage%20Mutant%20Ninja%20Turtles%20IV%20-%20Turtles%20in%20Time%20%28USA%29.zip`,
    cover_url: getUrls(SNES, 'Teenage Mutant Ninja Turtles IV - Turtles in Time (USA)').cover,
    artwork_url: getUrls(SNES, 'Teenage Mutant Ninja Turtles IV - Turtles in Time (USA)').art,
    rom_size: 1048576,
    emulator_core: 'snes9x',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'SuperPunchOutUSA',
    title: 'Super Punch-Out!!',
    system: 'SNES',
    system_id: 'snes',
    year: 1994,
    publisher: 'Nintendo',
    developer: 'Nintendo',
    players: 1,
    rom_url: `${MYRIENT_SNES}/Super%20Punch-Out%21%21%20%28USA%29.zip`,
    cover_url: getUrls(SNES, 'Super Punch-Out!! (USA)').cover,
    artwork_url: getUrls(SNES, 'Super Punch-Out!! (USA)').art,
    rom_size: 2097152,
    emulator_core: 'snes9x',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'KirbySuperStarUSA',
    title: 'Kirby Super Star',
    system: 'SNES',
    system_id: 'snes',
    year: 1996,
    publisher: 'Nintendo',
    developer: 'HAL Laboratory',
    players: 2,
    rom_url: `${MYRIENT_SNES}/Kirby%20Super%20Star%20%28USA%29.zip`,
    cover_url: getUrls(SNES, 'Kirby Super Star (USA)').cover,
    artwork_url: getUrls(SNES, 'Kirby Super Star (USA)').art,
    rom_size: 4194304,
    emulator_core: 'snes9x',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'YoshisIslandUSA',
    title: "Super Mario World 2: Yoshi's Island",
    system: 'SNES',
    system_id: 'snes',
    year: 1995,
    publisher: 'Nintendo',
    developer: 'Nintendo',
    players: 1,
    rom_url: `${MYRIENT_SNES}/Super%20Mario%20World%202%20-%20Yoshi%27s%20Island%20%28USA%29.zip`,
    cover_url: getUrls(SNES, "Super Mario World 2 - Yoshi's Island (USA)").cover,
    artwork_url: getUrls(SNES, "Super Mario World 2 - Yoshi's Island (USA)").art,
    rom_size: 2097152,
    emulator_core: 'snes9x',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  // EXPANSION BATCH 4 - GENESIS / GBA / NES (25 Titles)
  // GENESIS
  {
    game_id: 'StreetsOfRage2USA',
    title: 'Streets of Rage 2',
    system: 'GENESIS',
    system_id: 'sega_genesis',
    year: 1992,
    publisher: 'Sega',
    developer: 'Sega',
    players: 2,
    rom_url: `${MYRIENT_GEN}/Streets%20of%20Rage%202%20%28USA%29.zip`,
    cover_url: getUrls(GEN, 'Streets of Rage 2 (USA)').cover,
    artwork_url: getUrls(GEN, 'Streets of Rage 2 (USA)').art,
    rom_size: 2097152,
    emulator_core: 'genesis_plus_gx',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'GunstarHeroesUSA',
    title: 'Gunstar Heroes',
    system: 'GENESIS',
    system_id: 'sega_genesis',
    year: 1993,
    publisher: 'Sega',
    developer: 'Treasure',
    players: 2,
    rom_url: `${MYRIENT_GEN}/Gunstar%20Heroes%20%28USA%29.zip`,
    cover_url: getUrls(GEN, 'Gunstar Heroes (USA)').cover,
    artwork_url: getUrls(GEN, 'Gunstar Heroes (USA)').art,
    rom_size: 1048576,
    emulator_core: 'genesis_plus_gx',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'ShinobiIIIUSA',
    title: 'Shinobi III: Return of the Ninja Master',
    system: 'GENESIS',
    system_id: 'sega_genesis',
    year: 1993,
    publisher: 'Sega',
    developer: 'Sega',
    players: 1,
    rom_url: `${MYRIENT_GEN}/Shinobi%20III%20-%20Return%20of%20the%20Ninja%20Master%20%28USA%29.zip`,
    cover_url: getUrls(GEN, 'Shinobi III - Return of the Ninja Master (USA)').cover,
    artwork_url: getUrls(GEN, 'Shinobi III - Return of the Ninja Master (USA)').art,
    rom_size: 1048576,
    emulator_core: 'genesis_plus_gx',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'PhantasyStarIVUSA',
    title: 'Phantasy Star IV',
    system: 'GENESIS',
    system_id: 'sega_genesis',
    year: 1993,
    publisher: 'Sega',
    developer: 'Sega',
    players: 1,
    rom_url: `${MYRIENT_GEN}/Phantasy%20Star%20IV%20%28USA%29.zip`,
    cover_url: getUrls(GEN, 'Phantasy Star IV (USA)').cover,
    artwork_url: getUrls(GEN, 'Phantasy Star IV (USA)').art,
    rom_size: 3145728,
    emulator_core: 'genesis_plus_gx',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'ComixZoneUSA',
    title: 'Comix Zone',
    system: 'GENESIS',
    system_id: 'sega_genesis',
    year: 1995,
    publisher: 'Sega',
    developer: 'Sega',
    players: 1,
    rom_url: `${MYRIENT_GEN}/Comix%20Zone%20%28USA%29.zip`,
    cover_url: getUrls(GEN, 'Comix Zone (USA)').cover,
    artwork_url: getUrls(GEN, 'Comix Zone (USA)').art,
    rom_size: 2097152,
    emulator_core: 'genesis_plus_gx',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'GoldenAxeUSA',
    title: 'Golden Axe',
    system: 'GENESIS',
    system_id: 'sega_genesis',
    year: 1989,
    publisher: 'Sega',
    developer: 'Sega',
    players: 2,
    rom_url: `${MYRIENT_GEN}/Golden%20Axe%20%28World%29.zip`,
    cover_url: getUrls(GEN, 'Golden Axe (World)').cover,
    artwork_url: getUrls(GEN, 'Golden Axe (World)').art,
    rom_size: 524288,
    emulator_core: 'genesis_plus_gx',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'RistarUSA',
    title: 'Ristar',
    system: 'GENESIS',
    system_id: 'sega_genesis',
    year: 1995,
    publisher: 'Sega',
    developer: 'Sega',
    players: 1,
    rom_url: `${MYRIENT_GEN}/Ristar%20%28USA%2C%20Europe%29.zip`,
    cover_url: getUrls(GEN, 'Ristar (USA, Europe)').cover,
    artwork_url: getUrls(GEN, 'Ristar (USA, Europe)').art,
    rom_size: 2097152,
    emulator_core: 'genesis_plus_gx',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'CastlevaniaBloodlinesUSA',
    title: 'Castlevania: Bloodlines',
    system: 'GENESIS',
    system_id: 'sega_genesis',
    year: 1994,
    publisher: 'Konami',
    developer: 'Konami',
    players: 1,
    rom_url: `${MYRIENT_GEN}/Castlevania%20-%20Bloodlines%20%28USA%29.zip`,
    cover_url: getUrls(GEN, 'Castlevania - Bloodlines (USA)').cover,
    artwork_url: getUrls(GEN, 'Castlevania - Bloodlines (USA)').art,
    rom_size: 1048576,
    emulator_core: 'genesis_plus_gx',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'ContraHardCorpsUSA',
    title: 'Contra: Hard Corps',
    system: 'GENESIS',
    system_id: 'sega_genesis',
    year: 1994,
    publisher: 'Konami',
    developer: 'Konami',
    players: 2,
    rom_url: `${MYRIENT_GEN}/Contra%20-%20Hard%20Corps%20%28USA%29.zip`,
    cover_url: getUrls(GEN, 'Contra - Hard Corps (USA)').cover,
    artwork_url: getUrls(GEN, 'Contra - Hard Corps (USA)').art,
    rom_size: 2097152,
    emulator_core: 'genesis_plus_gx',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'EarthwormJimUSA',
    title: 'Earthworm Jim',
    system: 'GENESIS',
    system_id: 'sega_genesis',
    year: 1994,
    publisher: 'Playmates',
    developer: 'Shiny Entertainment',
    players: 1,
    rom_url: `${MYRIENT_GEN}/Earthworm%20Jim%20%28USA%29.zip`,
    cover_url: getUrls(GEN, 'Earthworm Jim (USA)').cover,
    artwork_url: getUrls(GEN, 'Earthworm Jim (USA)').art,
    rom_size: 2097152,
    emulator_core: 'genesis_plus_gx',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  // GBA
  {
    game_id: 'MetroidFusionUSA',
    title: 'Metroid Fusion',
    system: 'GBA',
    system_id: 'gba',
    year: 2002,
    publisher: 'Nintendo',
    developer: 'Nintendo',
    players: 1,
    rom_url: `${MYRIENT_GBA}/Metroid%20Fusion%20%28USA%29.zip`,
    cover_url: getUrls(GBA, 'Metroid Fusion (USA)').cover,
    artwork_url: getUrls(GBA, 'Metroid Fusion (USA)').art,
    rom_size: 8388608,
    emulator_core: 'mgba',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'CastlevaniaAriaOfSorrowUSA',
    title: 'Castlevania: Aria of Sorrow',
    system: 'GBA',
    system_id: 'gba',
    year: 2003,
    publisher: 'Konami',
    developer: 'Konami',
    players: 1,
    rom_url: `${MYRIENT_GBA}/Castlevania%20-%20Aria%20of%20Sorrow%20%28USA%29.zip`,
    cover_url: getUrls(GBA, 'Castlevania - Aria of Sorrow (USA)').cover,
    artwork_url: getUrls(GBA, 'Castlevania - Aria of Sorrow (USA)').art,
    rom_size: 8388608,
    emulator_core: 'mgba',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'GoldenSunUSA',
    title: 'Golden Sun',
    system: 'GBA',
    system_id: 'gba',
    year: 2001,
    publisher: 'Nintendo',
    developer: 'Camelot',
    players: 1,
    rom_url: `${MYRIENT_GBA}/Golden%20Sun%20%28USA%2C%20Europe%29.zip`,
    cover_url: getUrls(GBA, 'Golden Sun (USA)').cover,
    artwork_url: getUrls(GBA, 'Golden Sun (USA)').art,
    rom_size: 8388608,
    emulator_core: 'mgba',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'AdvanceWarsUSA',
    title: 'Advance Wars',
    system: 'GBA',
    system_id: 'gba',
    year: 2001,
    publisher: 'Nintendo',
    developer: 'Intelligent Systems',
    players: 4,
    rom_url: `${MYRIENT_GBA}/Advance%20Wars%20%28USA%29.zip`,
    cover_url: getUrls(GBA, 'Advance Wars (USA)').cover,
    artwork_url: getUrls(GBA, 'Advance Wars (USA)').art,
    rom_size: 4194304,
    emulator_core: 'mgba',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'FireEmblemUSA',
    title: 'Fire Emblem',
    system: 'GBA',
    system_id: 'gba',
    year: 2003,
    publisher: 'Nintendo',
    developer: 'Intelligent Systems',
    players: 1,
    rom_url: `${MYRIENT_GBA}/Fire%20Emblem%20%28USA%2C%20Australia%29.zip`,
    cover_url: getUrls(GBA, 'Fire Emblem (USA)').cover,
    artwork_url: getUrls(GBA, 'Fire Emblem (USA)').art,
    rom_size: 16777216,
    emulator_core: 'mgba',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'MarioLuigiSuperstarSagaUSA',
    title: 'Mario & Luigi: Superstar Saga',
    system: 'GBA',
    system_id: 'gba',
    year: 2003,
    publisher: 'Nintendo',
    developer: 'AlphaDream',
    players: 1,
    rom_url: `${MYRIENT_GBA}/Mario%20%26%20Luigi%20-%20Superstar%20Saga%20%28USA%29.zip`,
    cover_url: getUrls(GBA, 'Mario & Luigi - Superstar Saga (USA)').cover,
    artwork_url: getUrls(GBA, 'Mario & Luigi - Superstar Saga (USA)').art,
    rom_size: 16777216,
    emulator_core: 'mgba',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'FinalFantasyTacticsAdvanceUSA',
    title: 'Final Fantasy Tactics Advance',
    system: 'GBA',
    system_id: 'gba',
    year: 2003,
    publisher: 'Square Enix',
    developer: 'Square',
    players: 1,
    rom_url: `${MYRIENT_GBA}/Final%20Fantasy%20Tactics%20Advance%20%28USA%29.zip`,
    cover_url: getUrls(GBA, 'Final Fantasy Tactics Advance (USA)').cover,
    artwork_url: getUrls(GBA, 'Final Fantasy Tactics Advance (USA)').art,
    rom_size: 8388608,
    emulator_core: 'mgba',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'WarioWareIncUSA',
    title: 'WarioWare, Inc.: Mega Microgame$!',
    system: 'GBA',
    system_id: 'gba',
    year: 2003,
    publisher: 'Nintendo',
    developer: 'Nintendo',
    players: 1,
    rom_url: `${MYRIENT_GBA}/WarioWare%2C%20Inc.%20-%20Mega%20Microgame%24%21%20%28USA%29.zip`,
    cover_url: getUrls(GBA, 'WarioWare, Inc. - Mega Microgame$! (USA)').cover,
    artwork_url: getUrls(GBA, 'WarioWare, Inc. - Mega Microgame$! (USA)').art,
    rom_size: 8388608,
    emulator_core: 'mgba',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  // NES
  {
    game_id: 'MetroidNESUSA',
    title: 'Metroid',
    system: 'NES',
    system_id: 'nes',
    year: 1986,
    publisher: 'Nintendo',
    developer: 'Nintendo',
    players: 1,
    rom_url: `${MYRIENT_NES}/Metroid%20%28USA%29.zip`,
    cover_url: getUrls(NES, 'Metroid (USA)').cover,
    artwork_url: getUrls(NES, 'Metroid (USA)').art,
    rom_size: 131072,
    emulator_core: 'fceumm',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'LegendOfZeldaNESUSA',
    title: 'The Legend of Zelda',
    system: 'NES',
    system_id: 'nes',
    year: 1986,
    publisher: 'Nintendo',
    developer: 'Nintendo',
    players: 1,
    rom_url: `${MYRIENT_NES}/Legend%20of%20Zelda%2C%20The%20%28USA%29.zip`,
    cover_url: getUrls(NES, 'Legend of Zelda, The (USA)').cover,
    artwork_url: getUrls(NES, 'Legend of Zelda, The (USA)').art,
    rom_size: 131072,
    emulator_core: 'fceumm',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'SuperMarioBros3USA',
    title: 'Super Mario Bros. 3',
    system: 'NES',
    system_id: 'nes',
    year: 1988,
    publisher: 'Nintendo',
    developer: 'Nintendo',
    players: 2,
    rom_url: `${MYRIENT_NES}/Super%20Mario%20Bros.%203%20%28USA%29.zip`,
    cover_url: getUrls(NES, 'Super Mario Bros. 3 (USA)').cover,
    artwork_url: getUrls(NES, 'Super Mario Bros. 3 (USA)').art,
    rom_size: 393216,
    emulator_core: 'fceumm',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'MegaMan2USA',
    title: 'Mega Man 2',
    system: 'NES',
    system_id: 'nes',
    year: 1988,
    publisher: 'Capcom',
    developer: 'Capcom',
    players: 1,
    rom_url: `${MYRIENT_NES}/Mega%20Man%202%20%28USA%29.zip`,
    cover_url: getUrls(NES, 'Mega Man 2 (USA)').cover,
    artwork_url: getUrls(NES, 'Mega Man 2 (USA)').art,
    rom_size: 262144,
    emulator_core: 'fceumm',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'Castlevania3USA',
    title: "Castlevania III: Dracula's Curse",
    system: 'NES',
    system_id: 'nes',
    year: 1989,
    publisher: 'Konami',
    developer: 'Konami',
    players: 1,
    rom_url: `${MYRIENT_NES}/Castlevania%20III%20-%20Dracula%27s%20Curse%20%28USA%29.zip`,
    cover_url: getUrls(NES, "Castlevania III - Dracula's Curse (USA)").cover,
    artwork_url: getUrls(NES, "Castlevania III - Dracula's Curse (USA)").art,
    rom_size: 393216,
    emulator_core: 'fceumm',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'PunchOutNESUSA',
    title: 'Punch-Out!!',
    system: 'NES',
    system_id: 'nes',
    year: 1987,
    publisher: 'Nintendo',
    developer: 'Nintendo',
    players: 1,
    rom_url: `${MYRIENT_NES}/Punch-Out%21%21%20%28USA%29.zip`,
    cover_url: getUrls(NES, 'Punch-Out!! (USA)').cover,
    artwork_url: getUrls(NES, 'Punch-Out!! (USA)').art,
    rom_size: 262144,
    emulator_core: 'fceumm',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'ContraNESUSA',
    title: 'Contra',
    system: 'NES',
    system_id: 'nes',
    year: 1988,
    publisher: 'Konami',
    developer: 'Konami',
    players: 2,
    rom_url: `${MYRIENT_NES}/Contra%20%28USA%29.zip`,
    cover_url: getUrls(NES, 'Contra (USA)').cover,
    artwork_url: getUrls(NES, 'Contra (USA)').art,
    rom_size: 131072,
    emulator_core: 'fceumm',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  // EXPANSION BATCH 5 - N64 / PSX (25 Titles)
  // N64
  {
    game_id: 'SuperMario64USA',
    title: 'Super Mario 64',
    system: 'N64',
    system_id: 'n64',
    year: 1996,
    publisher: 'Nintendo',
    developer: 'Nintendo',
    players: 1,
    rom_url: `${MYRIENT_N64}/Super%20Mario%2064%20%28USA%29.zip`,
    cover_url: getUrls(N64, 'Super Mario 64 (USA)').cover,
    artwork_url: getUrls(N64, 'Super Mario 64 (USA)').art,
    rom_size: 8388608,
    emulator_core: 'mupen64plus_next',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'MarioKart64USA',
    title: 'Mario Kart 64',
    system: 'N64',
    system_id: 'n64',
    year: 1996,
    publisher: 'Nintendo',
    developer: 'Nintendo',
    players: 4,
    rom_url: `${MYRIENT_N64}/Mario%20Kart%2064%20%28USA%29.zip`,
    cover_url: getUrls(N64, 'Mario Kart 64 (USA)').cover,
    artwork_url: getUrls(N64, 'Mario Kart 64 (USA)').art,
    rom_size: 12582912,
    emulator_core: 'mupen64plus_next',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'LegendOfZeldaOcarinaOfTimeUSA',
    title: 'The Legend of Zelda: Ocarina of Time',
    system: 'N64',
    system_id: 'n64',
    year: 1998,
    publisher: 'Nintendo',
    developer: 'Nintendo',
    players: 1,
    rom_url: `${MYRIENT_N64}/Legend%20of%20Zelda%2C%20The%20-%20Ocarina%20of%20Time%20%28USA%29.zip`,
    cover_url: getUrls(N64, 'Legend of Zelda, The - Ocarina of Time (USA)').cover,
    artwork_url: getUrls(N64, 'Legend of Zelda, The - Ocarina of Time (USA)').art,
    rom_size: 33554432,
    emulator_core: 'mupen64plus_next',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'LegendOfZeldaMajorasMaskUSA',
    title: "The Legend of Zelda: Majora's Mask",
    system: 'N64',
    system_id: 'n64',
    year: 2000,
    publisher: 'Nintendo',
    developer: 'Nintendo',
    players: 1,
    rom_url: `${MYRIENT_N64}/Legend%20of%20Zelda%2C%20The%20-%20Majora%27s%20Mask%20%28USA%29.zip`,
    cover_url: getUrls(N64, "Legend of Zelda, The - Majora's Mask (USA)").cover,
    artwork_url: getUrls(N64, "Legend of Zelda, The - Majora's Mask (USA)").art,
    rom_size: 33554432,
    emulator_core: 'mupen64plus_next',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'SuperSmashBrosUSA',
    title: 'Super Smash Bros.',
    system: 'N64',
    system_id: 'n64',
    year: 1999,
    publisher: 'Nintendo',
    developer: 'HAL Laboratory',
    players: 4,
    rom_url: `${MYRIENT_N64}/Super%20Smash%20Bros.%20%28USA%29.zip`,
    cover_url: getUrls(N64, 'Super Smash Bros. (USA)').cover,
    artwork_url: getUrls(N64, 'Super Smash Bros. (USA)').art,
    rom_size: 16777216,
    emulator_core: 'mupen64plus_next',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'GoldenEye007USA',
    title: 'GoldenEye 007',
    system: 'N64',
    system_id: 'n64',
    year: 1997,
    publisher: 'Nintendo',
    developer: 'Rare',
    players: 4,
    rom_url: `${MYRIENT_N64}/GoldenEye%20007%20%28USA%29.zip`,
    cover_url: getUrls(N64, 'GoldenEye 007 (USA)').cover,
    artwork_url: getUrls(N64, 'GoldenEye 007 (USA)').art,
    rom_size: 12582912,
    emulator_core: 'mupen64plus_next',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'StarFox64USA',
    title: 'Star Fox 64',
    system: 'N64',
    system_id: 'n64',
    year: 1997,
    publisher: 'Nintendo',
    developer: 'Nintendo',
    players: 4,
    rom_url: `${MYRIENT_N64}/Star%20Fox%2064%20%28USA%29.zip`,
    cover_url: getUrls(N64, 'Star Fox 64 (USA)').cover,
    artwork_url: getUrls(N64, 'Star Fox 64 (USA)').art,
    rom_size: 12582912,
    emulator_core: 'mupen64plus_next',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'BanjoKazooieUSA',
    title: 'Banjo-Kazooie',
    system: 'N64',
    system_id: 'n64',
    year: 1998,
    publisher: 'Nintendo',
    developer: 'Rare',
    players: 1,
    rom_url: `${MYRIENT_N64}/Banjo-Kazooie%20%28USA%29.zip`,
    cover_url: getUrls(N64, 'Banjo-Kazooie (USA)').cover,
    artwork_url: getUrls(N64, 'Banjo-Kazooie (USA)').art,
    rom_size: 16777216,
    emulator_core: 'mupen64plus_next',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'PaperMarioUSA',
    title: 'Paper Mario',
    system: 'N64',
    system_id: 'n64',
    year: 2000,
    publisher: 'Nintendo',
    developer: 'Intelligent Systems',
    players: 1,
    rom_url: `${MYRIENT_N64}/Paper%20Mario%20%28USA%29.zip`,
    cover_url: getUrls(N64, 'Paper Mario (USA)').cover,
    artwork_url: getUrls(N64, 'Paper Mario (USA)').art,
    rom_size: 41943040,
    emulator_core: 'mupen64plus_next',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'WaveRace64USA',
    title: 'Wave Race 64',
    system: 'N64',
    system_id: 'n64',
    year: 1996,
    publisher: 'Nintendo',
    developer: 'Nintendo',
    players: 2,
    rom_url: `${MYRIENT_N64}/Wave%20Race%2064%20%28USA%29.zip`,
    cover_url: getUrls(N64, 'Wave Race 64 (USA)').cover,
    artwork_url: getUrls(N64, 'Wave Race 64 (USA)').art,
    rom_size: 8388608,
    emulator_core: 'mupen64plus_next',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'PerfectDarkUSA',
    title: 'Perfect Dark',
    system: 'N64',
    system_id: 'n64',
    year: 2000,
    publisher: 'Rare',
    developer: 'Rare',
    players: 4,
    rom_url: `${MYRIENT_N64}/Perfect%20Dark%20%28USA%29.zip`,
    cover_url: getUrls(N64, 'Perfect Dark (USA)').cover,
    artwork_url: getUrls(N64, 'Perfect Dark (USA)').art,
    rom_size: 33554432,
    emulator_core: 'mupen64plus_next',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: '1080SnowboardingUSA',
    title: '1080° Snowboarding',
    system: 'N64',
    system_id: 'n64',
    year: 1998,
    publisher: 'Nintendo',
    developer: 'Nintendo',
    players: 2,
    rom_url: `${MYRIENT_N64}/1080%20Snowboarding%20%28USA%29.zip`,
    cover_url: getUrls(N64, '1080 Snowboarding (USA)').cover,
    artwork_url: getUrls(N64, '1080 Snowboarding (USA)').art,
    rom_size: 16777216,
    emulator_core: 'mupen64plus_next',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  // PSX
  {
    game_id: 'CastlevaniaSOTNUSA',
    title: 'Castlevania: Symphony of the Night',
    system: 'PSX',
    system_id: 'psx',
    year: 1997,
    publisher: 'Konami',
    developer: 'Konami',
    players: 1,
    rom_url: `${MYRIENT_PSX}/Castlevania%20-%20Symphony%20of%20the%20Night%20%28USA%29.chd`,
    cover_url: getUrls(PSX, 'Castlevania - Symphony of the Night (USA)').cover,
    artwork_url: getUrls(PSX, 'Castlevania - Symphony of the Night (USA)').art,
    rom_size: 360000000,
    emulator_core: 'pcsx_rearmed',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'MetalGearSolidUSA',
    title: 'Metal Gear Solid',
    system: 'PSX',
    system_id: 'psx',
    year: 1998,
    publisher: 'Konami',
    developer: 'Konami',
    players: 1,
    rom_url: `${MYRIENT_PSX}/Metal%20Gear%20Solid%20%28USA%29%20%28Disc%201%29.chd`,
    cover_url: getUrls(PSX, 'Metal Gear Solid (USA)').cover,
    artwork_url: getUrls(PSX, 'Metal Gear Solid (USA)').art,
    rom_size: 600000000,
    emulator_core: 'pcsx_rearmed',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'FinalFantasyVIIUSA',
    title: 'Final Fantasy VII',
    system: 'PSX',
    system_id: 'psx',
    year: 1997,
    publisher: 'Sony Computer Entertainment',
    developer: 'Square',
    players: 1,
    rom_url: `${MYRIENT_PSX}/Final%20Fantasy%20VII%20%28USA%29%20%28Disc%201%29.chd`,
    cover_url: getUrls(PSX, 'Final Fantasy VII (USA)').cover,
    artwork_url: getUrls(PSX, 'Final Fantasy VII (USA)').art,
    rom_size: 600000000,
    emulator_core: 'pcsx_rearmed',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'Tekken3USA',
    title: 'Tekken 3',
    system: 'PSX',
    system_id: 'psx',
    year: 1998,
    publisher: 'Namco',
    developer: 'Namco',
    players: 2,
    rom_url: `${MYRIENT_PSX}/Tekken%203%20%28USA%29.chd`,
    cover_url: getUrls(PSX, 'Tekken 3 (USA)').cover,
    artwork_url: getUrls(PSX, 'Tekken 3 (USA)').art,
    rom_size: 500000000,
    emulator_core: 'pcsx_rearmed',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'GranTurismo2USA',
    title: 'Gran Turismo 2',
    system: 'PSX',
    system_id: 'psx',
    year: 1999,
    publisher: 'Sony Computer Entertainment',
    developer: 'Polyphony Digital',
    players: 2,
    rom_url: `${MYRIENT_PSX}/Gran%20Turismo%202%20%28USA%29%20%28Arcade%20Mode%29.chd`,
    cover_url: getUrls(PSX, 'Gran Turismo 2 (USA)').cover,
    artwork_url: getUrls(PSX, 'Gran Turismo 2 (USA)').art,
    rom_size: 600000000,
    emulator_core: 'pcsx_rearmed',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'ResidentEvil2USA',
    title: 'Resident Evil 2',
    system: 'PSX',
    system_id: 'psx',
    year: 1998,
    publisher: 'Capcom',
    developer: 'Capcom',
    players: 1,
    rom_url: `${MYRIENT_PSX}/Resident%20Evil%202%20%28USA%29%20%28Disc%201%29%20%28Leon%29.chd`,
    cover_url: getUrls(PSX, 'Resident Evil 2 (USA)').cover,
    artwork_url: getUrls(PSX, 'Resident Evil 2 (USA)').art,
    rom_size: 400000000,
    emulator_core: 'pcsx_rearmed',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'SilentHillUSA',
    title: 'Silent Hill',
    system: 'PSX',
    system_id: 'psx',
    year: 1999,
    publisher: 'Konami',
    developer: 'Team Silent',
    players: 1,
    rom_url: `${MYRIENT_PSX}/Silent%20Hill%20%28USA%29.chd`,
    cover_url: getUrls(PSX, 'Silent Hill (USA)').cover,
    artwork_url: getUrls(PSX, 'Silent Hill (USA)').art,
    rom_size: 350000000,
    emulator_core: 'pcsx_rearmed',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'TonyHawksProSkater2USA',
    title: "Tony Hawk's Pro Skater 2",
    system: 'PSX',
    system_id: 'psx',
    year: 2000,
    publisher: 'Activision',
    developer: 'Neversoft',
    players: 2,
    rom_url: `${MYRIENT_PSX}/Tony%20Hawk%27s%20Pro%20Skater%202%20%28USA%29.chd`,
    cover_url: getUrls(PSX, "Tony Hawk's Pro Skater 2 (USA)").cover,
    artwork_url: getUrls(PSX, "Tony Hawk's Pro Skater 2 (USA)").art,
    rom_size: 450000000,
    emulator_core: 'pcsx_rearmed',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'CrashBandicootWarpedUSA',
    title: 'Crash Bandicoot: Warped',
    system: 'PSX',
    system_id: 'psx',
    year: 1998,
    publisher: 'Sony Computer Entertainment',
    developer: 'Naughty Dog',
    players: 1,
    rom_url: `${MYRIENT_PSX}/Crash%20Bandicoot%20-%20Warped%20%28USA%29.chd`,
    cover_url: getUrls(PSX, 'Crash Bandicoot - Warped (USA)').cover,
    artwork_url: getUrls(PSX, 'Crash Bandicoot - Warped (USA)').art,
    rom_size: 400000000,
    emulator_core: 'pcsx_rearmed',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'SpyroYearOfTheDragonUSA',
    title: 'Spyro: Year of the Dragon',
    system: 'PSX',
    system_id: 'psx',
    year: 2000,
    publisher: 'Sony Computer Entertainment',
    developer: 'Insomniac Games',
    players: 1,
    rom_url: `${MYRIENT_PSX}/Spyro%20-%20Year%20of%20the%20Dragon%20%28USA%29.chd`,
    cover_url: getUrls(PSX, 'Spyro - Year of the Dragon (USA)').cover,
    artwork_url: getUrls(PSX, 'Spyro - Year of the Dragon (USA)').art,
    rom_size: 400000000,
    emulator_core: 'pcsx_rearmed',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'PaRappaTheRapperUSA',
    title: 'PaRappa the Rapper',
    system: 'PSX',
    system_id: 'psx',
    year: 1997,
    publisher: 'Sony Computer Entertainment',
    developer: 'NanaOn-Sha',
    players: 1,
    rom_url: `${MYRIENT_PSX}/PaRappa%20the%20Rapper%20%28USA%29.chd`,
    cover_url: getUrls(PSX, 'PaRappa the Rapper (USA)').cover,
    artwork_url: getUrls(PSX, 'PaRappa the Rapper (USA)').art,
    rom_size: 300000000,
    emulator_core: 'pcsx_rearmed',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'StreetFighterAlpha3USA',
    title: 'Street Fighter Alpha 3',
    system: 'PSX',
    system_id: 'psx',
    year: 1999,
    publisher: 'Capcom',
    developer: 'Capcom',
    players: 2,
    rom_url: `${MYRIENT_PSX}/Street%20Fighter%20Alpha%203%20%28USA%29.chd`,
    cover_url: getUrls(PSX, 'Street Fighter Alpha 3 (USA)').cover,
    artwork_url: getUrls(PSX, 'Street Fighter Alpha 3 (USA)').art,
    rom_size: 400000000,
    emulator_core: 'pcsx_rearmed',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  },
  {
    game_id: 'ChronoCrossUSA',
    title: 'Chrono Cross',
    system: 'PSX',
    system_id: 'psx',
    year: 2000,
    publisher: 'Square',
    developer: 'Square',
    players: 1,
    rom_url: `${MYRIENT_PSX}/Chrono%20Cross%20%28USA%29%20%28Disc%201%29.chd`,
    cover_url: getUrls(PSX, 'Chrono Cross (USA)').cover,
    artwork_url: getUrls(PSX, 'Chrono Cross (USA)').art,
    rom_size: 600000000,
    emulator_core: 'pcsx_rearmed',
    compatibility_status: 'verified',
    checksum: null,
    playable: true
  }
];
